#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-bcat
Version  : 0.6.2
Release  : 8
URL      : https://rubygems.org/downloads/bcat-0.6.2.gem
Source0  : https://rubygems.org/downloads/bcat-0.6.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-bcat-bin
BuildRequires : ruby
BuildRequires : rubygem-rack
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-test-unit

%description
bcat
http://github.com/rtomayko/bcat
git clone git://github.com/rtomayko/bcat.git
gem install bcat

%package bin
Summary: bin components for the rubygem-bcat package.
Group: Binaries

%description bin
bin components for the rubygem-bcat package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n bcat-0.6.2
gem spec %{SOURCE0} -l --ruby > rubygem-bcat.gemspec

%build
gem build rubygem-bcat.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
bcat-0.6.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/bcat-0.6.2 && rake test TESTOPTS="-v" && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/bcat-0.6.2.gem
/usr/lib64/ruby/gems/2.3.0/gems/bcat-0.6.2/CONTRIBUTING
/usr/lib64/ruby/gems/2.3.0/gems/bcat-0.6.2/COPYING
/usr/lib64/ruby/gems/2.3.0/gems/bcat-0.6.2/INSTALLING
/usr/lib64/ruby/gems/2.3.0/gems/bcat-0.6.2/README
/usr/lib64/ruby/gems/2.3.0/gems/bcat-0.6.2/RELEASING
/usr/lib64/ruby/gems/2.3.0/gems/bcat-0.6.2/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/bcat-0.6.2/bcat.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/bcat-0.6.2/bin/a2h
/usr/lib64/ruby/gems/2.3.0/gems/bcat-0.6.2/bin/bcat
/usr/lib64/ruby/gems/2.3.0/gems/bcat-0.6.2/bin/btee
/usr/lib64/ruby/gems/2.3.0/gems/bcat-0.6.2/contrib/bman
/usr/lib64/ruby/gems/2.3.0/gems/bcat-0.6.2/lib/bcat.rb
/usr/lib64/ruby/gems/2.3.0/gems/bcat-0.6.2/lib/bcat/ansi.rb
/usr/lib64/ruby/gems/2.3.0/gems/bcat-0.6.2/lib/bcat/browser.rb
/usr/lib64/ruby/gems/2.3.0/gems/bcat-0.6.2/lib/bcat/html.rb
/usr/lib64/ruby/gems/2.3.0/gems/bcat-0.6.2/lib/bcat/reader.rb
/usr/lib64/ruby/gems/2.3.0/gems/bcat-0.6.2/lib/bcat/server.rb
/usr/lib64/ruby/gems/2.3.0/gems/bcat-0.6.2/man/a2h.1
/usr/lib64/ruby/gems/2.3.0/gems/bcat-0.6.2/man/a2h.1.ronn
/usr/lib64/ruby/gems/2.3.0/gems/bcat-0.6.2/man/bcat.1
/usr/lib64/ruby/gems/2.3.0/gems/bcat-0.6.2/man/bcat.1.ronn
/usr/lib64/ruby/gems/2.3.0/gems/bcat-0.6.2/man/btee.1
/usr/lib64/ruby/gems/2.3.0/gems/bcat-0.6.2/man/btee.1.ronn
/usr/lib64/ruby/gems/2.3.0/gems/bcat-0.6.2/man/index.html
/usr/lib64/ruby/gems/2.3.0/gems/bcat-0.6.2/test/contest.rb
/usr/lib64/ruby/gems/2.3.0/gems/bcat-0.6.2/test/test_bcat_a2h.rb
/usr/lib64/ruby/gems/2.3.0/gems/bcat-0.6.2/test/test_bcat_ansi.rb
/usr/lib64/ruby/gems/2.3.0/gems/bcat-0.6.2/test/test_bcat_browser.rb
/usr/lib64/ruby/gems/2.3.0/gems/bcat-0.6.2/test/test_bcat_head_parser.rb
/usr/lib64/ruby/gems/2.3.0/specifications/bcat-0.6.2.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/a2h
/usr/bin/bcat
/usr/bin/btee
